# Generated by Django 4.1.2 on 2022-11-07 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_subcategory_alter_product_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('subcategory',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
