# Generated by Django 4.1.2 on 2022-11-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(db_index=True, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
