# Generated by Django 4.1.2 on 2022-11-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_product_color_delete_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=25, verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Сообщения')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('is_processing', models.BooleanField(default=False, verbose_name='Активно')),
            ],
            options={
                'ordering': ('-date', 'is_processing'),
            },
        ),
    ]
