# Generated by Django 4.1.2 on 2022-11-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-date', 'is_processing'), 'verbose_name': 'Cвяжитесь с нами', 'verbose_name_plural': 'Свзяжитесь с нами'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_processing',
            field=models.BooleanField(default=False, verbose_name='Ответить'),
        ),
    ]
