# Generated by Django 4.1.2 on 2023-03-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_contact_options_alter_contact_is_processing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/products/no-image.png', upload_to='images/products/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='product',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='used_quantity',
            field=models.IntegerField(null=True, verbose_name='Количество Б/У на складе'),
        ),
    ]
