# Generated by Django 4.1.2 on 2023-07-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(db_index=True, max_length=35, primary_key=True, serialize=False, unique=True),
        ),
    ]
