# Generated by Django 4.1.2 on 2023-07-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Б/У'),
        ),
    ]
