# Generated by Django 4.1.2 on 2022-11-21 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0012_alter_contact_options_alter_contact_is_processing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Імя')),
                ('surname', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефону')),
                ('email', models.CharField(db_index=True, max_length=150, verbose_name='Email')),
                ('delivery', models.CharField(choices=[('Самовивіз', 'Самовивозом'), ('Новою почтою', 'Доставка Новою почтою')], max_length=50, verbose_name='Спосіб доставки')),
                ('address', models.CharField(max_length=150, verbose_name='Адреса або відділення НП')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('post', models.CharField(max_length=10, verbose_name='Поштовий індекс')),
                ('payment', models.CharField(choices=[('Готівкою', 'Оплата готівкою'), ('Картою', 'Оплата картою'), ('Накладним платежем', 'Накладним платежем')], max_length=50, verbose_name='Спосіб оплати')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=True, verbose_name='Заказ активен?')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created', 'paid'),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('count', models.IntegerField(default=1, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
